[package]
org = "ballerinax"
name = "ai.milvus"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["milvus", "vector_database", "vector_search"]
repository = "https://github.com/ballerina-platform/module-ballerinax-milvus"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = false

[[dependency]]
org = "ballerinax"
name = "milvus"
version = "1.0.0"
repository="local"
